### ISSUE TITLE
Respond to Uskudarli on Piazza about group communicator

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/project_repo#10]
Respond to Uskudarli on Piazza about group communicator

**Comment by cakyel** [comment]
Communicator Response to the Instructor
Dear Instructor,
 
This is Hayri Can Akyel and the main purpose of my post is to introduce myself to you. I will be the communicator of Group 2 throughout the semester. I will be waiting questions from you about our group, if there is any.
 
I would be glad if you can answer my questions below about our way of communication.
 
May I include Group 2 when I send a message to you?
How frequently would you like to receive updates from the communicator?
Piazza is the only platform to communicate when we are out of class, right?
Will I always be the only person who can contact with you, or is there any exceptions?
 
 
Best regards,
Can
