### ISSUE TITLE
Weekly Meeting Location Poll - Results

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/project_repo#12]
This issue will be closed when everyone fills the form and the weekly meeting location is determined.

**Comment by barisozcanli** [comment]
done, assigned to Can

**Comment by cakyel** [comment]
Beşiktaş is defined as our meeting location on Thursdays. Please make a comment before the poll is closed, if there is any hesitation about the decision.
 
We want to come together as quickly as possible in order to determine our main requirements. 
 
We will make a Skype meeting on Wednesday, in advance. This is a reminder note so that we can gather up.
