### ISSUE TITLE
Clone Github Project Commit And Push (Orkun)

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/project_repo#2]
Clone the project on specified URL : https://github.com/swe574-2015fall-group2/project_repo.git

$ git clone https://github.com/swe574-2015fall-group2/project_repo.git

modify the readme.md file then add to staging

$ git add readme.md

commit with :

$ git commit -m "modified readme.md"

then push

$ git push

**Comment by OrkunKocyigit** [comment]
Already done
