### ISSUE TITLE
Prepare mock up for "Search Results" page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/project_repo#24]
Search Results page will be like a search engine.

There can be tabs to filter search results, such as Text, Image, File.

Search input will be text. If a user clicks Image button, image results regarding to the text input will be listed.

**Comment by cakyel** [comment]
The link to Piazza mock up note and further discussions:
https://piazza.com/class/if3ll4yun9p306?cid=27

**Comment by barisozcanli** [comment]
I created 3 pages for notes results, image results and file results.

@ssurucu @cakyel @OrkunKocyigit @recepgunay53 @mehmetcelikel please check and approve the issue if appropriate.

**Comment by cakyel** [comment]
I have done slight revisions. I approve the mock up and close this issue to obtain our progress. If you have any concerns, please reopen this issue.

https://mockups-gdrive-bmpr.appspot.com/?state=%7B"action":"open","ids":%5B"0B7VdZKhGGqYubDV1Ym9VZTBReHc"%5D,"userId":"106756995791607384723"%7D#
