### ISSUE TITLE
Prepare mock up for "User Profile" page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/project_repo#25]
The mock up will include personal details and privacy settings for messaging such as:

- Every user can send me a message.
- Only users in my groups can send me a message.
- No user can send me a message.

**Comment by cakyel** [comment]
The link to Piazza mock up note and further discussions:
https://piazza.com/class/if3ll4yun9p306?cid=27

**Comment by barisozcanli** [comment]
I created a My Profile page.

@cakyel @ssurucu @OrkunKocyigit @recepgunay53 @mehmetcelikel please check the mock up and approve this issue

**Comment by cakyel** [comment]
I have done slight revisions. I approve the mock up and close this issue to obtain our progress. If you have any concerns, please reopen this issue.

**Comment by cakyel** [comment]
https://mockups-gdrive-bmpr.appspot.com/?state=%7B"action":"open","ids":%5B"0B7VdZKhGGqYubDV1Ym9VZTBReHc"%5D,"userId":"106756995791607384723"%7D#
