### ISSUE TITLE
Prepare mock up for "Members" page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/project_repo#27]
The page for listing members in order to send a message.

We will decide later if this page is group specific, or general, or both.

**Comment by cakyel** [comment]
The link to Piazza mock up note and further discussions:
https://piazza.com/class/if3ll4yun9p306?cid=27

**Comment by barisozcanli** [comment]
I created a basic members list page.

@ssurucu and @cakyel please check the mock up and approve the issue if appropriate.

https://mockups-gdrive-bmpr.appspot.com/?state={%22action%22:%22open%22,%22ids%22:[%220B7VdZKhGGqYubDV1Ym9VZTBReHc%22],%22userId%22:%22106756995791607384723%22}#
