### ISSUE TITLE
Prepare mock up for "Documents" page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/project_repo#29]
Some files, images and papers may be uploaded in different times, and they may get lost in the news feed.

So there is a need for "Documents" page in a group to classify them in chronological order.

**Comment by cakyel** [comment]
The link to Piazza mock up note and further discussions:
https://piazza.com/class/if3ll4yun9p306?cid=27

**Comment by barisozcanli** [comment]
I created a documents page.

@ssurucu  and @cakyel please check the mockup and approve this issue if appropriate
@OrkunKocyigit @mehmetcelikel @recepgunay53 guys, you can also check and approve. Thanks!

https://mockups-gdrive-bmpr.appspot.com/?state={%22action%22:%22open%22,%22ids%22:[%220B7VdZKhGGqYubDV1Ym9VZTBReHc%22],%22userId%22:%22106756995791607384723%22}#
