### ISSUE TITLE
Clone Github Project Commit And Push (Can)

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/project_repo#3]
Clone the project on specified URL : https://github.com/swe574-2015fall-group2/project_repo.git

$ git clone https://github.com/swe574-2015fall-group2/project_repo.git

modify the readme.md file then add to staging

$ git add readme.md

commit with :

$ git commit -m "modified readme.md"

then push

$ git push

**Comment by cakyel** [comment]
Commit is done and named as: Readme File Test Commit - Can
