### ISSUE TITLE
Prepare mock up for "Note" page

### ISSUE THREAD

**Issue by cakyel** [swe574-2015fall-group2/project_repo#30]
There will be "Note" entries such as "Thursday Meeting Notes" or "Mock Up Examples" as we see in Piazza. 

The page forms of a Discussion and Note are similar but they differ in the meaning we give them. So we need two different mock ups.

**Comment by cakyel** [comment]
The link to Piazza mock up note and further discussions:
https://piazza.com/class/if3ll4yun9p306?cid=27

**Comment by barisozcanli** [comment]
I renamed "discussion detail" to "note detail" and made some modifications on it according to our new "note" term.

@ssurucu  and @cakyel please check the mockup and approve this issue

**Comment by barisozcanli** [comment]
I may have misinterpreted this issue. I made modifications according to "Note Details". If this issue refers to "Notes Listing" a new issue must be created.
