### ISSUE TITLE
Notify uskudarli about git repo

### ISSUE THREAD

**Issue by barisozcanli** [swe574-2015fall-group2/project_repo#7]
Suzan Uskudarli should be notified about this Git Group and repository

**Comment by cakyel** [comment]
Group 2 - 1st Week Report
Hello,
 
You can find our first week accomplishments below.
 
Hayri Can Akyel has been chosen as the messenger of Group 2.
GitHub repository has been created:
https://github.com/swe574-2015fall-group2/project_repo/
Every member cloned the repository to local and pushed a test commit successfully.
Weekly meeting day has been agreed on Thursday.
